# -*- coding: utf-8 -*-
"""TASK BASED ON KNN LOGISTIC AND LINEAR .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6roW2PmR1Vf79_64QEq91VW-oLV96Kq
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
df = pd.read_csv('/content/diabetes.csv')
df.head()

X = df.drop('Outcome', axis=1)
y = df['Outcome']

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

Scaler=StandardScaler()
x_train_scaled = Scaler.fit_transform(x_train)
x_test_scaled = Scaler.transform(x_test)

knn= KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train_scaled,y_train)

y_pred=knn.predict(x_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Assuming 'df' is your DataFrame and 'Outcome' is the target variable
# Separate features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize features (important for distance-based algorithms like KNN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the KNN classifier (let's start with k=5)
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test_scaled)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

print("\n--- Logistic Regression with liblinear solver ---")
# Initialize the Logistic Regression classifier with 'liblinear' solver
# 'liblinear' is a good choice for small datasets and supports L1 and L2 regularization.
logistic_model_liblinear = LogisticRegression(solver='liblinear', random_state=42)

# Train the model
logistic_model_liblinear.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred_liblinear = logistic_model_liblinear.predict(X_test_scaled)

# Evaluate the model's accuracy
accuracy_liblinear = accuracy_score(y_test, y_pred_liblinear)
print(f"Logistic Regression (liblinear) Model Accuracy: {accuracy_liblinear:.4f}")

print("\n--- Logistic Regression with lbfgs solver ---")
# Initialize the Logistic Regression classifier with 'lbfgs' solver
# 'lbfgs' is a good choice for larger datasets and supports L2 regularization.
logistic_model_lbfgs = LogisticRegression(solver='lbfgs', random_state=42)

# Train the model
logistic_model_lbfgs.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred_lbfgs = logistic_model_lbfgs.predict(X_test_scaled)

# Evaluate the model's accuracy
accuracy_lbfgs = accuracy_score(y_test, y_pred_lbfgs)
print(f"Logistic Regression (lbfgs) Model Accuracy: {accuracy_lbfgs:.4f}")